print("Good morning! Let's play a game of Mad Libs!")
t=int(input("Enter the number of times you want to play: "))
for _ in range(t):
    
    print("Choose a story:")
    print("1.The Chaotic School Day")
    print("2.The Weird Vacation")
    print("3.The Horror Story")
    print("4.The Superhero Disaster")
    print("5.The Awkward First Date")
    choice = input("Enter the number of your choice: ")
    match choice:
        case "1":
            name=input("Enter a name: ")
            color=input("Enter a color: ")
            object=input("Enter an object: ")
            verb=input("Enter a verb(V4): ")
            animal=input("Enter an animal: ")
            food=input("Enter a food: ")
            song=input("Enter a song: ")
            print(f"Today, {name} came to school wearing a {color} hat and carrying a {object}. During math class, the teacher suddenly started {verb} across the classroom. Everyone screamed when a giant {animal} appeared near the window. At lunch, {name} accidentally spilled {food} on the principal’s shoes and had to sing {song} as punishment.")
        case "2":
            place=input("Enter a place: ")
            name=input("Enter a name: ")
            vehicle=input("Enter a type of vehicle: ")
            food=input("Enter a food: ")
            adjective=input("Enter an adjective: ")
            verb=input("Enter a verb(V4): ")
            plural_animal=input("Enter a plural animal: ")
            object=input("Enter an object: ")
            print(f"Last summer, I went to {place} with my best friend {name}. We traveled there using a flying {vehicle} powered entirely by {food}. On the first day, we met a {adjective} tour guide who only communicated by {verb}. At night, a group of {plural_animal} stole our {object} and disappeared into the jungle.")
        case "3":
            name=input("Enter a name: ")
            room=input("Enter a room/place: ")
            object=input("Enter an object: ")
            animal=input("Enter an animal: ")
            food=input("Enter a food: ")
            verb=input("Enter a verb(V4): ")
            plural_noun=input("Enter a plural noun: ")
            print(f"It was midnight when {name} heard a strange noise coming from the {room}. Slowly, they picked up a {object} and walked toward the sound. Suddenly, a terrifying {animal} jumped out screaming “Give me your {food}!” Terrified, {name} escaped by {verb} through the window and landed in a pile of {plural_noun}.")
        case "4":
            city=input("Enter a city: ")
            funny_name=input("Enter a funny name: ")
            superheroname=input("Enter a superhero name: ")
            superpower=input("Enter a superpower: ")
            object=input("Enter an object: ")
            plural_animals=input("Enter a plural animal: ")
            random_phrase=input("Enter a random phrase: ")
            fooditem=input("Enter a food item: ")  
            print(f"The city of {city} was under attack by the evil villain {funny_name}. Only the superhero {superheroname} could save the day using their power of {superpower}. Armed with a magical {object}, they fought thousands of giant {plural_animals} while the crowd chanted {random_phrase}. In the end, the villain slipped on a {fooditem} and was defeated.")
        case "5":
            name=input("Enter a name: ")
            place=input("Enter a place: ")
            adjective=input("Enter an adjective: ")
            food=input("Enter a food: ")
            
            verb=input("Enter a verb(V4): ")
            animal=input("Enter an animal: ")
            vehicle=input("Enter a type of vehicle: ")
            print(f"Yesterday, {name} went on a date to {place} wearing a very {adjective} outfit. Everything was going well until the waiter dropped a plate of {food} onto their lap. Trying to impress their date, they began {verb} on the table while a nearby {animal} stared aggressively. Somehow, the date ended with both of them riding away on a {vehicle} into the sunset.")
        case _:
            print("Invalid choice. Please run the program again and select a number from 1 to 5.")